name: appmoodo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^0.4.0
  charts_flutter: ^0.10.0
  cupertino_icons: ^1.0.2
  fl_chart: ^0.35.0
  flutter_riverpod: ^0.14.0+1
  flutter_svg: ^0.21.0+1
  intl: ^0.17.0

dependency_overrides:
  appwrite:
    git:
      url: git@github.com:appwrite/sdk-for-flutter
      ref: feat-null-safety-new

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
