name: appmoodo
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^0.4.0
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.13.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
